export const SIGN_OUT = {
  REQUEST: 'SIGN_OUT_REQUEST',
  SUCCESS: 'SIGN_OUT_SUCCESS',
}

export const SIGN_IN = {
  REQUEST: 'SIGN_IN_REQUEST',
  SUCCESS: 'SIGN_IN_SUCCESS',
  FAILURE: 'SIGN_IN_FAILURE',
  CANCEL: 'IGN_IN_CANCEL',
}
