export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const POST_SIGN_OUT = 'POST_SIGN_OUT'
export const POST_SIGN_IN = {
  REQUEST: 'POST_SIGN_IN_REQUEST',
  SUCCESS: 'POST_SIGN_IN_SUCCESS',
  FAILURE: 'POST_SIGN_IN_FAILURE',
  CANCEL: 'POST_SIGN_IN_CANCEL',
}
export const TOGGLE_SIGN_IN_FORM = 'TOGGLE_SIGN_IN_FORM'
